version: '3.7'

services:
  db:
    build: ./db
    container_name: sparkLoaderWeb2-db
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=DKyyePqFavqpbNLa
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

  app:
    build: ./app
    container_name: sparkLoaderWeb2-app
    command: sh -c "/usr/src/app/run_server.sh"
    depends_on:
      - db
    volumes:
      - ./app/sparkLoaderWeb2:/usr/src/app/sparkLoaderWeb2
    ports:
      - "8081:8000"
    env_file:
      - ./.env.dev

volumes:
  postgres_data: